apiVersion: batch/v1
kind: Job
metadata:
  name: client-job
spec: 
  template:         
    metadata:
      name: client-job
    spec:
      containers:
      - name: client
        image: python:latest
        command:
        - python
        - request.py